version: 0.2

phases:
  install:
    runtime-versions:
        docker: 18
    commands:
      - echo Installing app dependencies...
      - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
      - chmod 700 get_helm.sh
      - ./get_helm.sh
  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-10)
      - IMAGE_TAG=${COMMIT_HASH}
      - LATEST="$BRANCH-latest"
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_CLUSTER_NAME
      - |
        kubectl create secret docker-registry regcred \
        --docker-server=https://index.docker.io/v1/ \
        --docker-username=$DOCKER_USERNAME \
        --docker-password=$DOCKER_PASSWORD \
        --docker-email=$DOCKER_EMAIL \
        --namespace=$NAMESPACE || true
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - |
        docker build -f ./docker/Dockerfile -t $IMAGE_REPO_NAME:$IMAGE_TAG -t $IMAGE_REPO_NAME:$LATEST .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$LATEST $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$LATEST
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$LATEST
      - |
        if expr "${use_rds}" : 'false' >/dev/null; then
          helm upgrade db ./kubernetes/helm/database \
          --install \
          --set namespace=$NAMESPACE \
          --set DB_VERSION=$DB_VERSION \
          --set DB_DATABASE=$DB_DATABASE \
          --set DB_USERNAME=$DB_USERNAME
        fi
      - echo Installing helm chart
      - |
        helm upgrade backend ./kubernetes/helm/app \
        --install \
        --set image.repo=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG \
        --set namespace=$NAMESPACE \
        --set DB_HOST=$DB_HOST \
        --set DB_PORT=$DB_PORT \
        --set DB_NAME=$DB_NAME \
        --set DB_USERNAME=$DB_USERNAME
