version: '3'

services:
  backend:
    build:
      dockerfile: Dockerfile
      args:
        - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  postgres:
    image: "postgres:12.5"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: titldb


