@url = http://localhost:8000

###

GET {{url}}/api/ HTTP/1.1

###
GET {{url}}/health  HTTP/1.1

###

POST {{url}}/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "isaac@email.com",
    "password":"P@ssw0rd"
}

###

POST https://webhook.site/f444ed40-5789-40c1-901d-e3b9047b9051 HTTP/1.1
content-type: application/json

{
    "email": "isaac@email.com",
    "password":"P@ssw0rd"
}


### 

POST {{url}}/hook/onboarding HTTP/1.1
content-type: application/json

{
    "slug": "submit/212566480340553/",
    "q3_fullName3": {
        "first": "Apen",
        "last": "Administrator"
    },
    "q4_address4": {
        "addr_line1": "Kampala",
        "addr_line2": "Uganda",
        "city": "asdasdasd",
        "state": "asdasdasd",
        "postal": "asdasdasd"
    },
    "q5_phoneNumber5": {
        "full": "(256) 772-8293"
    },
    "q6_email6": "apen.co@outlook.com",
    "q8_howDid8": "Newspaper",
    "q9_other": "",
    "q11_feedbackAbout11": "https://webhook.site/f444ed40-5789-40c1-901d-e3b9047b9051",
    "q12_suggestionsIf": "https://webhook.site/f444ed40-5789-40c1-901d-e3b9047b9051",
    "q13_willYou": [
        "Maybe"
    ],
    "q14_pleaseGive14": [
        [
            "12123adasd",
            "123123123",
            "asdasdasd"
        ],
        [
            "123123123",
            "adsasdasd",
            "asdasdasda"
        ]
    ],
    "preview": "true"
}