apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
  encrypted: "true"
