apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awsebs
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
