name: Passing Tests
on: [push]
jobs:
  passing-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Yarn install
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
      - run: yarn test
